name: Publish to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
     - name: Commit and push to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git switch --track origin/gh-pages
          git merge origin/main
          git commit --allow-empty -m "Publish /site to GitHub Pages" || true
          git subtree push --prefix site gh-pages
